# Generated by Django 3.2.9 on 2021-11-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parking1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('flatnumber', models.IntegerField(max_length=100)),
                ('parkingno', models.CharField(max_length=100)),
                ('pourchno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='parking2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('flatnumber', models.IntegerField(max_length=100)),
                ('parkingno', models.CharField(max_length=100)),
                ('pourchno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='parking3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('flatnumber', models.IntegerField(max_length=100)),
                ('parkingno', models.CharField(max_length=100)),
                ('pourchno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='parking4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('flatnumber', models.IntegerField(max_length=100)),
                ('parkingno', models.CharField(max_length=100)),
                ('pourchno', models.IntegerField()),
            ],
        ),
    ]
