# Generated by Django 3.2.9 on 2021-11-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking1',
            name='flatnumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parking1',
            name='pourchno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parking2',
            name='flatnumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parking2',
            name='pourchno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parking3',
            name='flatnumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parking3',
            name='pourchno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parking4',
            name='flatnumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parking4',
            name='pourchno',
            field=models.CharField(max_length=100),
        ),
    ]
