# Generated by Django 3.2.9 on 2021-11-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20211116_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking1',
            name='pourchno',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
