# Generated by Django 3.2.9 on 2021-11-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_parking1_pourchno'),
    ]

    operations = [
        migrations.CreateModel(
            name='overalldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('flatnumber', models.CharField(max_length=100)),
                ('parkingno', models.CharField(max_length=100)),
                ('pourchno', models.CharField(max_length=100)),
            ],
        ),
    ]
